[workspace]
resolver = "2"
members = [
    "crates/diver-geom",
    "crates/diver-memory",
    "crates/diver-presence",
    "crates/diver-search",
    "crates/diver-shot",
    "src-tauri"
]

[workspace.package]
license = "AGPL-3.0-only"

[workspace.dependencies]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true